title: Fetching web pages with requests
hero_image: images/banner.png
description: generic-python-requests description
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
interests: ""
technologies: "python"
steps:
  - title: Fetching web pages with requests
