---
title: Obteniendo p치ginas web con solicitudes
hero_image: images/banner.png
description: Obteniendo datos de p치ginas web usando las solicitudes de m칩dulos de Python
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - title: Obteniendo p치ginas web con solicitudes
